spring.application.name=SpringBootday4_Jpa_crud

server.port=9999
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/jsp/

#viewresolver

Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
Spring.datasource.url=jdbc:mysql://localhost:3306/college
Spring.datasource.username=root
Spring.datasource.password=root

#jpa properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.dialect=org.hibernate.dialect.MySQL8Dialect

